server:
  port: 8001

spring:
#  datasource:
#    username: link
#    password: goodluck
#    url: jdbc:mysql://117.72.41.106:3306/link?characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&serverTimezone=GMT%2B8
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    hikari:
#      connection-test-query: select 1
#      connection-timeout: 20000
#      idle-timeout: 300000
#      maximum-pool-size: 5
#      minimum-idle: 5
  datasource:
    # ShardingSphere 对 Driver 自定义，实现分库分表等隐藏逻辑
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    # ShardingSphere 配置文件路径
    url: jdbc:shardingsphere:classpath:shardingsphere-config-${databases.env:dev}.yaml
  data:
    redis:
      host: 127.0.0.1
      port: 6379
#      password: root
  mvc:
    view:
      prefix: /templates/
      suffix: .html
    static-path-pattern: /static/**
  web:
    resources:
      static-locations: classpath:/static/

# mybatis配置
mybatis-plus:
  config-location: classpath:/mybatis/config/mybatis-config.xml
  mapper-locations: classpath:/mybatis/mapper/*.xml

# 调用高德api的key 用户ip地区定位
short-link:
  domain: link.url
  stats:
    amap-key: 9ac0d8b53da3aa1e67706990002cbf8f
